"""Captcha admission — bot-generated, NO 3rd-party server (SimpleX v6.3, gate 4).

Per ``docs/skfed-consent-design.md`` (group-join consent / SimpleX toolkit): an
owner may require an unknown joiner to **pass a captcha generated by the directory
bot itself** — no external captcha service. The bot derives a challenge from an
injected per-call seed (deterministic, no ``Math.random``), shows the prompt, and
stores only a SHA-256 hash of the expected answer keyed by ``challenge_id`` (with a
TTL). ``verify`` is one-shot (consumed on success) and fails closed on a wrong
answer, an expired challenge, or one that has burned through its attempt budget.

The clock is injected so TTL expiry is testable without sleeping.
"""
import hashlib

import pytest

from skcomms.consent_captcha import Captcha, derive_challenge

SEED_A = b"seed-alpha-0001"
SEED_B = b"seed-bravo-0002"


@pytest.fixture
def captcha(tmp_path, monkeypatch):
    monkeypatch.setenv("SKCOMMS_HOME", str(tmp_path))
    return Captcha(agent="lumina", ttl_s=300, max_attempts=3)


# --- deterministic derivation (injected seed, no randomness) ----------------


def test_derive_is_deterministic_for_a_seed():
    cid1, prompt1, ans1 = derive_challenge(SEED_A)
    cid2, prompt2, ans2 = derive_challenge(SEED_A)
    assert (cid1, prompt1, ans1) == (cid2, prompt2, ans2)


def test_different_seeds_give_different_challenges():
    cid_a, _, _ = derive_challenge(SEED_A)
    cid_b, _, _ = derive_challenge(SEED_B)
    assert cid_a != cid_b


def test_derive_accepts_str_and_bytes_equivalently():
    assert derive_challenge("hello") == derive_challenge(b"hello")


# --- generate -> persisted hashed answer ------------------------------------


def test_generate_returns_challenge_id_and_prompt():
    pass  # exercised below with a real instance


def test_generate_stores_only_a_hash_not_the_plaintext(captcha):
    cid, prompt = captcha.generate(SEED_A)
    _, _, answer = derive_challenge(SEED_A)
    assert isinstance(cid, str) and cid
    assert isinstance(prompt, str) and prompt
    # The persisted row stores the SHA-256 hash of the answer, not the plaintext.
    raw = captcha._raw_row(cid)
    assert raw is not None
    # Row layout: (challenge_id, answer_hash, created_at, attempts, max_attempts, ttl)
    answer_hash = raw[1]
    assert answer_hash == hashlib.sha256(answer.encode()).hexdigest()
    assert answer_hash != answer


# --- verify: correct answer passes, wrong fails -----------------------------


def test_correct_answer_passes(captcha):
    cid, _ = captcha.generate(SEED_A)
    _, _, answer = derive_challenge(SEED_A)
    assert captcha.verify(cid, answer) is True


def test_wrong_answer_fails(captcha):
    cid, _ = captcha.generate(SEED_A)
    assert captcha.verify(cid, "definitely-wrong") is False


def test_unknown_challenge_fails(captcha):
    assert captcha.verify("no-such-challenge", "anything") is False


# --- one-shot consume -------------------------------------------------------


def test_success_consumes_challenge_one_shot(captcha):
    cid, _ = captcha.generate(SEED_A)
    _, _, answer = derive_challenge(SEED_A)
    assert captcha.verify(cid, answer) is True
    # Replaying the same (correct) answer must now fail — it was consumed.
    assert captcha.verify(cid, answer) is False
    assert captcha._raw_row(cid) is None


# --- TTL expiry -------------------------------------------------------------


def test_expired_challenge_fails(captcha):
    cid, _ = captcha.generate(SEED_A, now=1000.0)
    _, _, answer = derive_challenge(SEED_A)
    # 301s later, past the 300s TTL → expired, even with the right answer.
    assert captcha.verify(cid, answer, now=1301.0) is False
    # Expired row is reaped.
    assert captcha._raw_row(cid) is None


def test_within_ttl_still_valid(captcha):
    cid, _ = captcha.generate(SEED_A, now=1000.0)
    _, _, answer = derive_challenge(SEED_A)
    assert captcha.verify(cid, answer, now=1299.0) is True


# --- attempt budget ---------------------------------------------------------


def test_over_attempt_budget_fails_and_locks(tmp_path, monkeypatch):
    monkeypatch.setenv("SKCOMMS_HOME", str(tmp_path))
    cap = Captcha(agent="lumina", ttl_s=300, max_attempts=3)
    cid, _ = cap.generate(SEED_A)
    _, _, answer = derive_challenge(SEED_A)
    # Burn the 3-attempt budget with wrong answers.
    assert cap.verify(cid, "x1") is False
    assert cap.verify(cid, "x2") is False
    assert cap.verify(cid, "x3") is False
    # Budget exhausted → challenge is locked/reaped; even the correct answer fails.
    assert cap.verify(cid, answer) is False
    assert cap._raw_row(cid) is None


# --- persistence + isolation ------------------------------------------------


def test_challenge_survives_a_fresh_instance(tmp_path, monkeypatch):
    monkeypatch.setenv("SKCOMMS_HOME", str(tmp_path))
    cap = Captcha(agent="lumina")
    cid, _ = cap.generate(SEED_A)
    _, _, answer = derive_challenge(SEED_A)
    fresh = Captcha(agent="lumina")
    assert fresh.verify(cid, answer) is True


def test_per_agent_isolation(tmp_path, monkeypatch):
    monkeypatch.setenv("SKCOMMS_HOME", str(tmp_path))
    a = Captcha(agent="lumina")
    b = Captcha(agent="jarvis")
    cid, _ = a.generate(SEED_A)
    _, _, answer = derive_challenge(SEED_A)
    # jarvis never issued this challenge → cannot verify it.
    assert b.verify(cid, answer) is False
    # lumina still can.
    assert a.verify(cid, answer) is True
