"""Captcha admission — bot-generated, NO 3rd-party server (gate 4 / SimpleX v6.3).

Per ``docs/skfed-consent-design.md`` (group-join consent, "SimpleX toolkit,
verified, directly transferable"): groups are invite-only and an owner may require
an unknown joiner to **pass a captcha generated by the directory bot itself — no
3rd-party servers**. This is the sovereign analogue of a hosted CAPTCHA: the bot
*is* the challenge issuer and verifier.

Sovereign scheme (no ``Math.random``):

* The challenge is derived **deterministically from a per-call seed/nonce** that the
  caller injects (:func:`derive_challenge`). The same seed always yields the same
  ``(challenge_id, prompt, answer)`` — which makes the whole thing testable and lets
  the caller own nonce provenance (e.g. an envelope nonce, a CSPRNG draw, a ratchet
  output). The generator never reaches for ambient randomness itself.
* Only a **SHA-256 hash of the expected answer** is persisted, keyed by
  ``challenge_id``, with a ``created_at`` timestamp, an attempt counter, and the
  per-challenge ``ttl``/``max_attempts`` budget. The plaintext answer is never
  stored.
* :meth:`Captcha.verify` is **one-shot** (consumed on success) and **fails closed**
  on a wrong answer, an expired challenge (``now - created_at >= ttl``), or one that
  has burned through its attempt budget. Expired / exhausted rows are reaped.

State lives under ``skcomms_home()/consent/<agent>/captcha.db`` (SQLite, isolated
per agent), matching the :class:`~skcomms.consent.ContactStore` /
:class:`~skcomms.consent_greylist.Greylist` layout. The clock is injectable so TTL
expiry is testable without sleeping.

This module is purely additive: it imports the shared :func:`skcomms.home.skcomms_home`
primitive and does not touch :mod:`skcomms.consent`, ``api.py`` or ``cli.py`` — the
gate composes it (see the integration note in the module that wires the stack).
"""
from __future__ import annotations

import hashlib
import sqlite3
import time
from pathlib import Path
from typing import Optional, Tuple, Union

from .home import skcomms_home

#: Default time-to-live for an issued challenge (seconds). Node POLICY, not
#: protocol — a safe default; the caller may override per :class:`Captcha`.
DEFAULT_TTL_S = 300

#: Default number of wrong guesses tolerated before the challenge is locked/reaped.
DEFAULT_MAX_ATTEMPTS = 3

#: Arithmetic operators the derived prompt may use. Subtraction is normalised to a
#: non-negative result so the answer is always an unambiguous natural number.
_OPS = ("+", "-", "*")


def _consent_dir(agent: str) -> Path:
    """Per-agent consent state dir under ``skcomms_home()`` (created if absent).

    Mirrors :func:`skcomms.consent._consent_dir` so the captcha store lives
    alongside the contact/request/greylist stores for the same agent.
    """
    d = skcomms_home() / "consent" / agent
    d.mkdir(parents=True, exist_ok=True)
    return d


def _seed_bytes(seed: Union[str, bytes]) -> bytes:
    """Coerce an injected seed/nonce to bytes (``str`` is UTF-8 encoded)."""
    return seed if isinstance(seed, bytes) else str(seed).encode("utf-8")


def derive_challenge(seed: Union[str, bytes]) -> Tuple[str, str, str]:
    """Deterministically derive ``(challenge_id, prompt_text, answer)`` from *seed*.

    Pure and side-effect free: no randomness, no persistence. A given seed always
    maps to the same challenge, so the caller controls nonce provenance and the
    behaviour is fully testable. ``str`` and ``bytes`` seeds with the same content
    derive identically.

    The challenge is a small scrambled arithmetic prompt — a sovereign, human/agent
    solvable puzzle with a single unambiguous natural-number answer.

    Args:
        seed: The per-call seed/nonce (e.g. an envelope nonce or CSPRNG draw).

    Returns:
        Tuple of ``(challenge_id, prompt_text, answer)``. ``answer`` is what
        :meth:`Captcha.generate` stores *hashed*; it is returned here so the issuer
        (the bot) can drive verification, never sent to the solver.
    """
    sb = _seed_bytes(seed)
    digest = hashlib.sha256(b"skcomms-captcha-v1:" + sb).digest()
    # challenge_id: a stable, opaque handle derived from the seed (domain-separated
    # from the answer derivation so the id leaks nothing about the answer).
    challenge_id = hashlib.sha256(b"skcomms-captcha-cid:" + sb).hexdigest()[:16]

    a = (digest[0] % 9) + 1          # 1..9
    b = (digest[1] % 9) + 1          # 1..9
    op = _OPS[digest[2] % len(_OPS)]

    if op == "+":
        value = a + b
        lhs, rhs = a, b
    elif op == "-":
        lhs, rhs = max(a, b), min(a, b)   # normalise → non-negative
        value = lhs - rhs
    else:  # "*"
        value = a * b
        lhs, rhs = a, b

    prompt_text = f"Sovereign captcha — solve to be admitted: what is {lhs} {op} {rhs}?"
    return challenge_id, prompt_text, str(value)


class Captcha:
    """Per-agent bot-generated captcha admission: ``generate`` then one-shot ``verify``.

    No external captcha provider — the bot derives, issues, and checks the challenge
    itself. Persists only a SHA-256 hash of the expected answer (keyed by
    ``challenge_id``) plus a TTL + attempt budget, so a leaked store reveals no
    plaintext answers.

    Args:
        agent: The agent whose admission store this is (path isolation).
        ttl_s: Seconds an issued challenge stays valid.
        max_attempts: Wrong guesses tolerated before the challenge is locked/reaped.
    """

    def __init__(
        self,
        agent: str,
        *,
        ttl_s: float = DEFAULT_TTL_S,
        max_attempts: int = DEFAULT_MAX_ATTEMPTS,
    ) -> None:
        self.agent = agent
        self.ttl_s = ttl_s
        self.max_attempts = max_attempts
        self._db = _consent_dir(agent) / "captcha.db"
        with self._conn() as c:
            c.execute(
                "CREATE TABLE IF NOT EXISTS captcha ("
                "challenge_id TEXT PRIMARY KEY, "
                "answer_hash TEXT NOT NULL, "
                "created_at REAL NOT NULL, "
                "attempts INTEGER NOT NULL DEFAULT 0, "
                "max_attempts INTEGER NOT NULL, "
                "ttl REAL NOT NULL)"
            )

    def _conn(self) -> sqlite3.Connection:
        return sqlite3.connect(str(self._db))

    @staticmethod
    def _hash(answer: str) -> str:
        return hashlib.sha256(answer.encode("utf-8")).hexdigest()

    def generate(
        self, seed: Union[str, bytes], *, now: Optional[float] = None
    ) -> Tuple[str, str]:
        """Issue a challenge from *seed*; persist the hashed answer + TTL.

        Args:
            seed: Injected per-call seed/nonce (no ambient randomness is used).
            now: Injected clock (epoch seconds). Defaults to :func:`time.time`.

        Returns:
            ``(challenge_id, prompt_text)`` — the prompt is what gets shown to the
            joiner. The answer is stored hashed, never returned here.
        """
        if now is None:
            now = time.time()
        challenge_id, prompt_text, answer = derive_challenge(seed)
        with self._conn() as c:
            c.execute(
                "INSERT OR REPLACE INTO captcha "
                "(challenge_id, answer_hash, created_at, attempts, max_attempts, ttl) "
                "VALUES (?,?,?,?,?,?)",
                (challenge_id, self._hash(answer), now, 0, self.max_attempts, self.ttl_s),
            )
        return challenge_id, prompt_text

    def verify(
        self, challenge_id: str, answer: str, *, now: Optional[float] = None
    ) -> bool:
        """One-shot verify *answer* against the stored challenge.

        Fails closed (``False``) when the challenge is unknown, expired
        (``now - created_at >= ttl``), or has exhausted its attempt budget. On a
        correct answer the challenge is **consumed** (deleted) so it cannot be
        replayed; on a wrong answer the attempt counter increments and the
        challenge is reaped once the budget is spent.

        Args:
            challenge_id: The id returned by :meth:`generate`.
            answer: The solver's submitted answer.
            now: Injected clock (epoch seconds). Defaults to :func:`time.time`.

        Returns:
            ``True`` only if the answer is correct and the challenge was live.
        """
        if now is None:
            now = time.time()
        with self._conn() as c:
            row = c.execute(
                "SELECT answer_hash, created_at, attempts, max_attempts, ttl "
                "FROM captcha WHERE challenge_id=?",
                (challenge_id,),
            ).fetchone()
            if row is None:
                return False

            answer_hash, created_at, attempts, max_attempts, ttl = row

            # Expired → reap and fail closed (even a correct answer is too late).
            if now - created_at >= ttl:
                c.execute("DELETE FROM captcha WHERE challenge_id=?", (challenge_id,))
                return False

            # Budget already spent (defensive; we reap on exhaustion below).
            if attempts >= max_attempts:
                c.execute("DELETE FROM captcha WHERE challenge_id=?", (challenge_id,))
                return False

            if self._hash(answer) == answer_hash:
                # Correct → consume (one-shot).
                c.execute("DELETE FROM captcha WHERE challenge_id=?", (challenge_id,))
                return True

            # Wrong → burn one attempt; reap if that exhausts the budget.
            attempts += 1
            if attempts >= max_attempts:
                c.execute("DELETE FROM captcha WHERE challenge_id=?", (challenge_id,))
            else:
                c.execute(
                    "UPDATE captcha SET attempts=? WHERE challenge_id=?",
                    (attempts, challenge_id),
                )
            return False

    def _raw_row(self, challenge_id: str) -> Optional[tuple]:
        """Return the persisted row for *challenge_id* (or ``None``) — test/introspection aid."""
        with self._conn() as c:
            return c.execute(
                "SELECT challenge_id, answer_hash, created_at, attempts, max_attempts, ttl "
                "FROM captcha WHERE challenge_id=?",
                (challenge_id,),
            ).fetchone()
