"""``~/.skcapstone/skcomms/`` realm message tree scaffold (T4, ``479ce678``).

Builds the sovereign, Syncthing-shareable message tree::

    ~/.skcapstone/skcomms/
      .stignore                         # Syncthing ignore (volatile/local)
      <realm>/<operator>/<agent>/
        outbox/                         # messages this agent has sent
        inbox/                          # messages addressed to this agent

``realm``/``operator`` come from ``cluster.json`` (via :mod:`skcomms.cluster`);
``agent`` comes from :func:`skcomms.identity.resolve_self_identity` (preferring
the ``fqid`` agent component, falling back to the ``agent`` field).

The home root honors the ``SKCOMMS_HOME`` env override and defaults to
``~/.skcapstone/skcomms``. The scaffold is idempotent — re-running never clobbers
existing message files.
"""

from __future__ import annotations

import logging
import os
from pathlib import Path
from typing import Optional

from .cluster import get_operator, get_realm
from .identity import resolve_self_identity

logger = logging.getLogger("skcomms.home")

# Top-level .stignore — Syncthing ignores these volatile/local files so they
# never propagate to peers (PID/lock files, temp/partial writes, local logs).
STIGNORE_CONTENT = """\
// skcomms .stignore — Syncthing ignores volatile/local files.
// Generated by `skcomms init`; edit below the marker to add your own.
*.tmp
*.lock
*.partial
daemon.pid
*.pid
.DS_Store
logs/
*.log
// Per-node daemon state (nonce replay cache etc.) must NEVER sync between
// nodes: each node keeps its own replay history.
state/
"""


def skcomms_home() -> Path:
    """Resolve the skcomms home root.

    Honors the ``SKCOMMS_HOME`` env override; defaults to ``~/.skcapstone/skcomms``.

    Returns:
        Path: The (un-created) home root path.
    """
    override = os.environ.get("SKCOMMS_HOME")
    if override:
        return Path(override).expanduser()
    return Path.home() / ".skcapstone" / "skcomms"


def _agent_name(agent: Optional[str]) -> str:
    """Resolve the short agent name for path construction.

    Prefers the agent component of the resolved fqid (the realm-tree name),
    falls back to the resolver's ``agent`` field, then to ``agent`` arg.
    """
    ident = resolve_self_identity(agent)
    fqid = ident.get("fqid")
    if fqid and "@" in fqid:
        return fqid.split("@", 1)[0]
    return ident.get("agent") or agent or "local"


def scaffold(agent: Optional[str] = None) -> dict:
    """Create the ``~/.skcapstone/skcomms/<realm>/<operator>/<agent>/{outbox,inbox}`` tree.

    Idempotent — safe to re-run; existing files are preserved. Also writes a
    top-level ``.stignore`` if one does not already exist.

    Args:
        agent: Short agent name. ``None`` triggers env/identity resolution.

    Returns:
        Dict with resolved ``home``, ``realm``, ``operator``, ``agent``,
        ``agent_dir``, ``outbox``, ``inbox``, ``stignore`` paths.
    """
    home = skcomms_home()
    realm = get_realm()
    operator = get_operator()
    name = _agent_name(agent)

    agent_dir = home / realm / operator / name
    outbox = agent_dir / "outbox"
    inbox = agent_dir / "inbox"

    home.mkdir(parents=True, exist_ok=True)
    outbox.mkdir(parents=True, exist_ok=True)
    inbox.mkdir(parents=True, exist_ok=True)

    stignore = home / ".stignore"
    if not stignore.exists():
        stignore.write_text(STIGNORE_CONTENT, encoding="utf-8")

    logger.debug("scaffolded skcomms tree at %s", agent_dir)
    return {
        "home": home,
        "realm": realm,
        "operator": operator,
        "agent": name,
        "agent_dir": agent_dir,
        "outbox": outbox,
        "inbox": inbox,
        "stignore": stignore,
    }


def peer_inbox(to_fqid: str) -> Path:
    """Resolve the inbox path for a peer FQID within this skcomms home.

    ``<agent>@<operator>.<realm>`` maps to
    ``<home>/<realm>/<operator>/<agent>/inbox``. This is where a sender drops
    a message destined for that peer (shared via Syncthing).

    Args:
        to_fqid: Recipient FQID (``<agent>@<operator>.<realm>``).

    Returns:
        Path: The peer's inbox directory (not necessarily created).

    Raises:
        ValueError: If *to_fqid* is not a valid ``a@o.r`` FQID.
    """
    if "@" not in to_fqid or "." not in to_fqid.split("@", 1)[1]:
        raise ValueError(f"invalid fqid: {to_fqid!r} (expected <agent>@<operator>.<realm>)")
    agent, rest = to_fqid.split("@", 1)
    operator, realm = rest.split(".", 1)

    # SECURITY: the FQID is peer-controlled (a remote sender's to_fqid reaches
    # here via store-forward). Reject any component that could escape the home
    # tree — a value like "x@../../../../tmp/evil.z" would otherwise resolve
    # outside skcomms_home() into an attacker-chosen directory (arbitrary file
    # write of attacker-controlled .json content).
    for part in (agent, operator, realm):
        if not part or part in (".", "..") or "/" in part or "\\" in part or "\x00" in part:
            raise ValueError(f"invalid fqid component in {to_fqid!r}: {part!r}")

    home = skcomms_home().resolve()
    target = (home / realm / operator / agent / "inbox").resolve()
    if home not in target.parents:
        raise ValueError(f"fqid {to_fqid!r} escapes the skcomms home tree")
    return target
