"""``~/.skcapstone/skcomms/`` realm message tree scaffold (T4, ``479ce678``).

Builds the sovereign, Syncthing-shareable message tree::

    ~/.skcapstone/skcomms/
      .stignore                         # Syncthing ignore (volatile/local)
      <realm>/<operator>/<agent>/
        outbox/                         # messages this agent has sent
        inbox/                          # messages addressed to this agent

``realm``/``operator`` come from ``cluster.json`` (via :mod:`skcomms.cluster`);
``agent`` comes from :func:`skcomms.identity.resolve_self_identity` (preferring
the ``fqid`` agent component, falling back to the ``agent`` field).

The home root honors the ``SKCOMMS_HOME`` env override and defaults to
``~/.skcapstone/skcomms``. The scaffold is idempotent — re-running never clobbers
existing message files.
"""

from __future__ import annotations

import logging
import os
from pathlib import Path
from typing import Optional

from .cluster import get_operator, get_realm
from .identity import resolve_self_identity

logger = logging.getLogger("skcomms.home")

# The per-node state/ ignore block. Kept as its own constant so it can be
# appended verbatim to a pre-existing .stignore that predates the durable
# nonce cache (see ensure_state_ignored).
STIGNORE_STATE_BLOCK = """\
// Per-node daemon state (nonce replay cache etc.) must NEVER sync between
// nodes: each node keeps its own replay history.
state/
"""

# Top-level .stignore — Syncthing ignores these volatile/local files so they
# never propagate to peers (PID/lock files, temp/partial writes, local logs).
STIGNORE_CONTENT = """\
// skcomms .stignore — Syncthing ignores volatile/local files.
// Generated by `skcomms init`; edit below the marker to add your own.
*.tmp
*.lock
*.partial
daemon.pid
*.pid
.DS_Store
logs/
*.log
""" + STIGNORE_STATE_BLOCK


def skcomms_home() -> Path:
    """Resolve the skcomms home root.

    Honors the ``SKCOMMS_HOME`` env override; defaults to ``~/.skcapstone/skcomms``.

    Returns:
        Path: The (un-created) home root path.
    """
    override = os.environ.get("SKCOMMS_HOME")
    if override:
        return Path(override).expanduser()
    return Path.home() / ".skcapstone" / "skcomms"


def nonce_cache_dir() -> Path:
    """Resolve the NODE-LOCAL directory holding replay-guard nonce caches.

    Nonce caches are ephemeral per-node replay guards. They must never be
    shared or synced between nodes: two independent writers on one live WAL
    SQLite through file sync risk corruption and conflict copies, which
    defeats the durable-replay guarantee. On live fleets ``skcomms_home()``
    sits inside a Syncthing-shared tree (and the Syncthing folder may be
    rooted ABOVE the home, e.g. ``~/.skcapstone``, where the home's own
    ``.stignore`` has no effect), so the caches default OUTSIDE it:

    1. ``SKCOMMS_NONCE_CACHE_DIR`` env override (ops pin), else
    2. ``$XDG_STATE_HOME/skcomms/`` when ``XDG_STATE_HOME`` is set, else
    3. ``~/.local/state/skcomms/``.

    Returns:
        Path: The (un-created) node-local nonce-cache directory.
    """
    override = (os.environ.get("SKCOMMS_NONCE_CACHE_DIR") or "").strip()
    if override:
        return Path(override).expanduser()
    xdg = (os.environ.get("XDG_STATE_HOME") or "").strip()
    base = Path(xdg).expanduser() if xdg else Path.home() / ".local" / "state"
    return base / "skcomms"


def _migrate_legacy_nonce_db(old: Path, new: Path) -> None:
    """Best-effort ONE-TIME copy of a legacy synced nonce DB to the local path.

    Runs only when *new* does not exist and *old* does. Uses the SQLite
    backup API (WAL-safe, reads a consistent snapshot). If the legacy file
    cannot be read (e.g. corrupted by a Syncthing conflict, the very failure
    mode that motivated the move), the partial copy is removed and the cache
    starts FRESH instead of failing closed: that is safe because the replay
    guard is layered under the envelope freshness check, so a fresh cache
    only exposes envelopes captured within the freshness window
    (``DEFAULT_MAX_AGE_S``, 300s) around the cutover.
    """
    import sqlite3

    if new.exists() or not old.exists():
        return
    if old.resolve() == new.resolve():  # ops pinned the dir back onto the old path
        return
    try:
        src = sqlite3.connect(str(old))
        try:
            dst = sqlite3.connect(str(new))
            try:
                src.backup(dst)
                dst.commit()
            finally:
                dst.close()
        finally:
            src.close()
        logger.info("migrated legacy nonce cache %s -> %s", old, new)
    except Exception as exc:
        try:
            new.unlink(missing_ok=True)
        except OSError:  # pragma: no cover - cleanup is best-effort
            pass
        logger.warning(
            "legacy nonce cache %s not migrated (%s); starting fresh at %s "
            "(safe: replay exposure bounded by the envelope freshness window)",
            old,
            exc,
            new,
        )


def resolve_nonce_db(name: str) -> Path:
    """Resolve the node-local path for the replay-guard DB *name*.

    The directory comes from :func:`nonce_cache_dir` (never inside the
    synced ``skcomms_home()`` tree by default). On first resolution a
    healthy legacy DB at ``skcomms_home()/state/<name>`` is migrated once
    (see :func:`_migrate_legacy_nonce_db`); the legacy file itself is left
    in place for ops cleanup but is never written again. As a best-effort
    courtesy to live fleets, the legacy home's ``.stignore`` is also healed
    so any leftover ``state/`` DB stops syncing between nodes; since the
    active cache no longer lives there, a failure to do so is non-fatal.

    Args:
        name: DB file name, e.g. ``nonce_cache.db``.

    Returns:
        Path: The node-local DB path (parent directory created).
    """
    local = nonce_cache_dir()
    local.mkdir(parents=True, exist_ok=True)
    new = local / name
    try:
        legacy_home = skcomms_home()
        ensure_state_ignored(legacy_home)
        _migrate_legacy_nonce_db(legacy_home / "state" / name, new)
    except Exception as exc:  # pragma: no cover - legacy healing is optional
        logger.warning("legacy nonce-cache healing skipped: %s", exc)
    return new


def ensure_state_ignored(home: Optional[Path] = None) -> Path:
    """Idempotently ensure ``state/`` is Syncthing-ignored in ``<home>/.stignore``.

    Fresh scaffolds get the full :data:`STIGNORE_CONTENT` (which already
    ignores ``state/``), but a live deployment whose ``.stignore`` predates
    the durable nonce cache would otherwise sync ``state/nonce_cache.db``
    (a live WAL SQLite) between nodes: file-sync corruption risk, plus
    conflict copies mixing per-node replay history. This healer runs from
    both :func:`scaffold` and the api's nonce-store path resolution, so
    existing nodes are fixed on the next daemon start without operator
    hand-edits.

    Args:
        home: The skcomms home root. ``None`` resolves via :func:`skcomms_home`.

    Returns:
        Path: The ``.stignore`` path (written or already compliant).
    """
    root = home if home is not None else skcomms_home()
    root.mkdir(parents=True, exist_ok=True)
    stignore = root / ".stignore"
    if not stignore.exists():
        stignore.write_text(STIGNORE_CONTENT, encoding="utf-8")
        return stignore
    text = stignore.read_text(encoding="utf-8")
    if "state/" in (line.strip() for line in text.splitlines()):
        return stignore
    sep = "" if (not text or text.endswith("\n")) else "\n"
    stignore.write_text(text + sep + STIGNORE_STATE_BLOCK, encoding="utf-8")
    logger.info("appended per-node state/ ignore to existing %s", stignore)
    return stignore


def _agent_name(agent: Optional[str]) -> str:
    """Resolve the short agent name for path construction.

    Prefers the agent component of the resolved fqid (the realm-tree name),
    falls back to the resolver's ``agent`` field, then to ``agent`` arg.
    """
    ident = resolve_self_identity(agent)
    fqid = ident.get("fqid")
    if fqid and "@" in fqid:
        return fqid.split("@", 1)[0]
    return ident.get("agent") or agent or "local"


def scaffold(agent: Optional[str] = None) -> dict:
    """Create the ``~/.skcapstone/skcomms/<realm>/<operator>/<agent>/{outbox,inbox}`` tree.

    Idempotent, safe to re-run; existing files are preserved. Also ensures a
    top-level ``.stignore`` exists and ignores the per-node ``state/`` subtree
    (appending the block to a pre-existing ``.stignore`` that lacks it).

    Args:
        agent: Short agent name. ``None`` triggers env/identity resolution.

    Returns:
        Dict with resolved ``home``, ``realm``, ``operator``, ``agent``,
        ``agent_dir``, ``outbox``, ``inbox``, ``stignore`` paths.
    """
    home = skcomms_home()
    realm = get_realm()
    operator = get_operator()
    name = _agent_name(agent)

    agent_dir = home / realm / operator / name
    outbox = agent_dir / "outbox"
    inbox = agent_dir / "inbox"

    home.mkdir(parents=True, exist_ok=True)
    outbox.mkdir(parents=True, exist_ok=True)
    inbox.mkdir(parents=True, exist_ok=True)

    stignore = ensure_state_ignored(home)

    logger.debug("scaffolded skcomms tree at %s", agent_dir)
    return {
        "home": home,
        "realm": realm,
        "operator": operator,
        "agent": name,
        "agent_dir": agent_dir,
        "outbox": outbox,
        "inbox": inbox,
        "stignore": stignore,
    }


def peer_inbox(to_fqid: str) -> Path:
    """Resolve the inbox path for a peer FQID within this skcomms home.

    ``<agent>@<operator>.<realm>`` maps to
    ``<home>/<realm>/<operator>/<agent>/inbox``. This is where a sender drops
    a message destined for that peer (shared via Syncthing).

    Args:
        to_fqid: Recipient FQID (``<agent>@<operator>.<realm>``).

    Returns:
        Path: The peer's inbox directory (not necessarily created).

    Raises:
        ValueError: If *to_fqid* is not a valid ``a@o.r`` FQID.
    """
    if "@" not in to_fqid or "." not in to_fqid.split("@", 1)[1]:
        raise ValueError(f"invalid fqid: {to_fqid!r} (expected <agent>@<operator>.<realm>)")
    agent, rest = to_fqid.split("@", 1)
    operator, realm = rest.split(".", 1)

    # SECURITY: the FQID is peer-controlled (a remote sender's to_fqid reaches
    # here via store-forward). Reject any component that could escape the home
    # tree — a value like "x@../../../../tmp/evil.z" would otherwise resolve
    # outside skcomms_home() into an attacker-chosen directory (arbitrary file
    # write of attacker-controlled .json content).
    for part in (agent, operator, realm):
        if not part or part in (".", "..") or "/" in part or "\\" in part or "\x00" in part:
            raise ValueError(f"invalid fqid component in {to_fqid!r}: {part!r}")

    home = skcomms_home().resolve()
    target = (home / realm / operator / agent / "inbox").resolve()
    if home not in target.parents:
        raise ValueError(f"fqid {to_fqid!r} escapes the skcomms home tree")
    return target
