#!/usr/bin/env bash
# refresh-constraints.sh: regenerate constraints.txt from a clean resolve.
#
# Pins every runtime and dev dependency (plus the api, cli, crypto, and
# skcapstone extras the Dockerfile installs) to the exact versions a fresh
# install resolves today, so CI and deploys run one validated set instead of
# re-resolving to whatever is latest.
#
# The resolve runs inside python:3.12-slim (Docker), which is the deploy target
# (Dockerfile FROM python:3.12-slim) and the top of the CI matrix. That keeps
# the pins consistent with what actually ships, independent of whatever Python
# happens to be on the machine running this script.
#
# Usage (from the repo root):
#   scripts/refresh-constraints.sh
#
# Requires: Docker. After running, review `git diff constraints.txt`, run the
# test suite, and commit.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

if ! command -v docker >/dev/null 2>&1; then
    echo "error: docker is required to regenerate constraints.txt" >&2
    echo "       (the resolve runs in python:3.12-slim to match the deploy target)" >&2
    exit 1
fi

# The extras union below MUST stay in sync with the install paths that consume
# constraints.txt: CI installs .[dev]; the Dockerfile installs
# .[api,cli,skcapstone,crypto]. Resolving them together pins one coherent set.
EXTRAS="dev,api,cli,crypto,skcapstone"

echo "Resolving skcomms[${EXTRAS}] in python:3.12-slim ..." >&2

RAW="$(docker run --rm -v "$REPO_ROOT":/w -w /w python:3.12-slim bash -c '
    set -e
    python -m pip install --upgrade pip -q
    pip install -q ".['"$EXTRAS"']" >/dev/null 2>&1
    pip freeze --exclude-editable \
        | grep -v "^skcomms @" \
        | grep -viE "^(pkg-resources|setuptools|wheel|pip)=="
')"

{
    cat <<'HEADER'
# constraints.txt: pinned dependency set for reproducible installs.
#
# This file pins every runtime and dev dependency (plus the api, cli, crypto,
# and skcapstone extras that the Dockerfile installs) to the exact versions a
# clean resolve produced. Install with `-c constraints.txt` so a fresh machine,
# CI, and a deploy image all run the versions CI validated, instead of
# re-resolving to whatever is latest on the day.
#
# Consumers:
#   * CI (.github/workflows/): pip install -c constraints.txt -e ".[dev]"
#   * Dockerfile: pip install -c constraints.txt ".[api,cli,skcapstone,crypto]"
#   * bp/systemd bootstrap consumes this file automatically if present.
#
# A constraint on a package that a given install does not pull is inert, so the
# same file safely serves both the dev (CI) and the api/cli/skcapstone/crypto
# (Docker) install paths.
#
# REGENERATE (one command, requires Docker; matches the 3.12 deploy target):
#   scripts/refresh-constraints.sh
#
# See CONTRIBUTING.md ("Refreshing the dependency lock") for details.
# Generated by a clean resolve on python:3.12-slim. Do not hand-edit; regenerate.
HEADER
    printf '%s\n' "$RAW"
} > constraints.txt

echo "Wrote constraints.txt ($(grep -cvE '^\s*#|^\s*$' constraints.txt) pinned packages)." >&2
echo "Next: review 'git diff constraints.txt', run the test suite, then commit." >&2
